### ISSUE TITLE
NAT Gateways are not included in Always Free 

### ISSUE THREAD

**Issue by timothechauvet** [bkk87/oci-nextcloud-docker#1]
Hi, trying to get your config working, I found out that NAT Gateways aren't supported by Always Free tier, apparently it would work by creating a NAT Instance which sounds really hard to do. Found the solution here : [Oracle Communities](https://community.oracle.com/tech/apps-infra/discussion/4493649/unable-to-create-a-nat-gateway)

I'm working on my own fork to see if I can get this to work and bypass this restriction

**Comment by bkk87** [comment]
That's strange. NAT GWs have always been free for me. I just doubled checked in my Oracle web console. 
With no NAT GW in the private subnet, nextcloud will not work as it needs internet access for several things, e.g. downloading apps.

Also, I do not actively work on this docker stack anymore. I prefer podman instead of the docker daemon: https://github.com/bkk87/oci-nextcloud-podman

**Comment by timothechauvet** [comment]
> Also, I do not actively work on this docker stack anymore. I prefer podman instead of the docker daemon: https://github.com/bkk87/oci-nextcloud-podman

Thanks a lot, I'll try that one, maybe with a different account

Edit : also, are you still on the Free tier plan or did you add your card even though you pay 0$ ?

**Comment by timothechauvet** [comment]
Creating a new account fixed the problem with NAT Gateways
